/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;

import DAO.ClienteDAO;
import DAO.InventarioDAO;
import DAO.ProductoDAO;
import DAO.VentaDAO;
import DataClasses.Cliente;
import DataClasses.Empleado;
import DataClasses.Producto;
import DataClasses.ProductoVenta;
import DataClasses.Venta;
import java.awt.Color;
import java.awt.GridLayout;
import java.sql.Date;
import java.text.ParseException;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OrdSon
 */
public class PanelVendedor extends javax.swing.JFrame {

    /**
     * Creates new form PanelVendedor
     */
    JTextField[] textFields;
    Empleado empleado;
    double descuento = 0;
    double subtotal = 0;
    double total = 0;
    String textPresets[] = new String[]{"PROMOCODE", "NIT", "NOMBRE", "CODIGO"};
    ProductoDAO productoDAO = new ProductoDAO();
    ClienteDAO clienteDAO = new ClienteDAO();
    VentaDAO ventaDAO = new VentaDAO();
    InventarioDAO inventarioDAO = new InventarioDAO();
    Producto actual;
    LinkedList<ProductoVenta> listaCompra = new LinkedList<>();

    public PanelVendedor() {
        initComponents();
        JTextField[] textFields = {nitTxt, nombreProductoTxt, codigoProductoTxt};
        fillTable();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    public PanelVendedor(Empleado empleado) {
        this.empleado = empleado;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        JTextField[] textFields = {nitTxt, nombreProductoTxt, codigoProductoTxt};
        fillTable();
    }

    public DefaultTableModel fillTable() {
        Object header[] = new Object[]{"CODIGO", "NOMBRE", "MARCA", "PRECIO"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        for (ProductoVenta productoVenta : listaCompra) {
            model.addRow(new Object[]{productoVenta.getProducto().id(), productoVenta.getProducto().nombre(), productoVenta.getProducto().marca(),
                productoVenta.getProducto().precio()});
        }
        tablaVenta.setModel(model);
        return model;
    }

    private void calcTotal() {
        try {
            double sum = 0;
            for (int i = 0; i < tablaVenta.getRowCount(); i++) {
                sum = sum + Double.parseDouble(tablaVenta.getValueAt(i, 3).toString());
            }
            subTotalTxt.setText("Q. " + String.format("%,.2f", sum));
            subtotal = sum;
            if (sum >= 10000) {
                descuento = 10;
                sum = (sum - (sum * 0.1));
                total = sum;
                descuentoLbl.setText("10%");
            } else if (sum >= 5000) {
                descuento = 5;
                sum = (sum - (sum * 0.05));
                total = sum;

                descuentoLbl.setText("5%");
            } else if (sum >= 1000) {
                descuento = 2;
                sum = (sum - (sum * 0.02));
                total = sum;

                descuentoLbl.setText("2%");
            } else {
                descuento = 0;
                total = sum;

                descuentoLbl.setText("$$$");
            }
            totalLbl.setText("Q. " + String.format("%,.2f", sum));
        } catch (NumberFormatException e) {
        }
    }

    private Venta recopilarVenta() {
        //id_cliente, id_sucursal, id_empleado, descuento, subtotal, total

        try {
            String nit = nitTxt.getText();
            int idSucursal = empleado.sucursal();
            int idEmpleado = empleado.id();
            Venta nueva = new Venta(0, nit, idSucursal, idEmpleado, new Date(WIDTH), descuento, subtotal, total);
            return nueva;
        } catch (Exception e) {
            return null;
        }

    }

    private boolean darError() {
        StringBuilder sb = new StringBuilder();
        if (nitTxt.getText().isBlank()) {
            sb.append("DEBE HABER UN CLIENTE \n");
        }
        if (listaCompra.isEmpty()) {
            sb.append("LISTA DE PRODUCTOS VACÍA\n");
        }
        if (!sb.isEmpty()) {
            JOptionPane.showMessageDialog(null, sb.toString());
        }
        return !sb.isEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        descuentoLbl = new javax.swing.JLabel();
        cantidadSpinner = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        subTotalTxt = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        codigoProductoTxt = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        nombreProductoTxt = new javax.swing.JTextField();
        agregarButton = new javax.swing.JButton();
        quitarButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        nitTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombreClienteTxt = new javax.swing.JLabel();
        nuevoClienteButton = new javax.swing.JButton();
        cfButton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(600, 400));

        jButton4.setText("Finalizar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        jLabel8.setText("TOTAL:");

        jLabel9.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel9.setText("DESCUENTO:");

        totalLbl.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        totalLbl.setText("$$$");

        descuentoLbl.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        descuentoLbl.setText("$$$");

        cantidadSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantidadSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder("CANTIDAD"));

        jLabel10.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel10.setText("SUBTOTAL:");

        subTotalTxt.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        subTotalTxt.setText("$$$");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(totalLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descuentoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(subTotalTxt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(totalLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTotalTxt)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(descuentoLbl))
                .addContainerGap())
        );

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 90));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 90));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        codigoProductoTxt.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        codigoProductoTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("ID PRODUCTO"));
        codigoProductoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProductoTxtActionPerformed(evt);
            }
        });

        buscarButton.setFont(new java.awt.Font("Source Sans Pro Light", 0, 18)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        nombreProductoTxt.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        nombreProductoTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        nombreProductoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoTxtActionPerformed(evt);
            }
        });

        agregarButton.setFont(new java.awt.Font("Source Sans Pro Light", 0, 18)); // NOI18N
        agregarButton.setText("AGREGAR");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        quitarButton.setFont(new java.awt.Font("Source Sans Pro Light", 0, 18)); // NOI18N
        quitarButton.setText("QUITAR");
        quitarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(agregarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigoProductoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(nombreProductoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codigoProductoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreProductoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        nitTxt.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        nitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel1.setText("NIT:");

        nombreClienteTxt.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        nombreClienteTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreClienteTxt.setText("???");

        nuevoClienteButton.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        nuevoClienteButton.setText("NUEVO");
        nuevoClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoClienteButtonActionPerformed(evt);
            }
        });

        cfButton.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        cfButton.setText("C/F");
        cfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfButtonActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jButton8.setText("BUSCAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Source Sans Pro Light", 0, 18)); // NOI18N
        jButton5.setText("FINALIZAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8))
                    .addComponent(nombreClienteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevoClienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(nombreClienteTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevoClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVenta);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        try {
            cantidadSpinner.commitEdit();
            if (actual == null || nombreProductoTxt.getText().isBlank()) {
                actual = productoDAO.select(Integer.parseInt(codigoProductoTxt.getText()));
            }
            for (int i = 0; i < (Integer) cantidadSpinner.getValue(); i++) {
                listaCompra.add(new ProductoVenta(actual, 1));
            }
            fillTable();
            calcTotal();
            cantidadSpinner.setValue(1);
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error en codigo de producto");
        }
    }//GEN-LAST:event_agregarButtonActionPerformed


    private void codigoProductoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProductoTxtActionPerformed

    }//GEN-LAST:event_codigoProductoTxtActionPerformed

    private void nombreProductoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductoTxtActionPerformed

    }//GEN-LAST:event_nombreProductoTxtActionPerformed

    private void nitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitTxtActionPerformed

    }//GEN-LAST:event_nitTxtActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
    }//GEN-LAST:event_jPanel1MouseClicked

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        try {
            Producto producto = productoDAO.select(Integer.parseInt(codigoProductoTxt.getText()));
            nombreProductoTxt.setText(producto.nombre() + " " + producto.marca());
            this.actual = producto;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void quitarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarButtonActionPerformed
        try {
            int selectedRow = tablaVenta.getSelectedRow();
            listaCompra.remove(selectedRow);
            fillTable();
            calcTotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_quitarButtonActionPerformed

    private void cfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfButtonActionPerformed
        nombreClienteTxt.setText("C/F");
        nitTxt.setText("C/F");
    }//GEN-LAST:event_cfButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            String nit = nitTxt.getText();
            Cliente buscado = clienteDAO.select(nit);
            if (buscado == null) {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado");
            }
            nombreClienteTxt.setText(buscado.nombre());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void nuevoClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoClienteButtonActionPerformed
        JPanel nuevo = new JPanel(new GridLayout(5, 1));
        JLabel titleLbl = new JLabel("AÑADIR CLIENTE");
        JLabel nameLbl = new JLabel("NOMBRE");
        JTextField name = new JTextField(10);
        JLabel nitLbl = new JLabel("NIT");
        JTextField nit = new JTextField(10);
        nuevo.add(titleLbl);
        nuevo.add(nameLbl);
        nuevo.add(name);
        nuevo.add(nitLbl);
        nuevo.add(nit);
        JOptionPane.showMessageDialog(null, nuevo);

        if (!name.getText().isBlank() && !nit.getText().isBlank()) {
            clienteDAO.insert(new Cliente(nit.getText(), name.getText()));
            nitTxt.setText(nit.getText());
            nombreClienteTxt.setText(name.getText());
            return;
        }
        JOptionPane.showMessageDialog(null, "Datos invalidos");

    }//GEN-LAST:event_nuevoClienteButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (darError()) {
            return;
        }
        ventaDAO.insert(recopilarVenta(), listaCompra);
    }//GEN-LAST:event_jButton5ActionPerformed

    public void checkEmptyText() {
        for (JTextField textField : textFields) {
            if (textField.getText().isBlank()) {
                textField.setForeground(Color.LIGHT_GRAY);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JButton cfButton;
    private javax.swing.JTextField codigoProductoTxt;
    private javax.swing.JLabel descuentoLbl;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nitTxt;
    private javax.swing.JLabel nombreClienteTxt;
    private javax.swing.JTextField nombreProductoTxt;
    private javax.swing.JButton nuevoClienteButton;
    private javax.swing.JButton quitarButton;
    private javax.swing.JLabel subTotalTxt;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
