/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author OrdSon
 */
public class PanelAdmin extends javax.swing.JFrame {

    PanelSucursal ps = new PanelSucursal();
    PanelVentas pv = new PanelVentas();
    PanelEmpleado pe = new PanelEmpleado();
    PanelProducto pp = new PanelProducto();
    PanelCliente pc = new PanelCliente();
    PanelReportes pr = new PanelReportes();

    /**
     * Creates new form FrameAdmin
     */
    public PanelAdmin() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PanelAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PanelAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PanelAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

        tabSucursales.add(ps);
        tabVentas.add(pv);
        tabEmpleados.add(pe);
        tabProductos.add(pp);
        tabClientes.add(pc);
        tabReportes.add(pr);
        this.setSize(700, 635);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tabHolder = new javax.swing.JTabbedPane();
        tabSucursales = new javax.swing.JPanel();
        tabVentas = new javax.swing.JPanel();
        tabEmpleados = new javax.swing.JPanel();
        tabProductos = new javax.swing.JPanel();
        tabClientes = new javax.swing.JPanel();
        tabReportes = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 800));
        setPreferredSize(new java.awt.Dimension(700, 800));
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRADOR");
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMinimumSize(new java.awt.Dimension(625, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(625, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());

        tabHolder.setBackground(new java.awt.Color(102, 204, 255));
        tabHolder.setFont(new java.awt.Font("Source Sans Pro", 1, 12)); // NOI18N

        tabSucursales.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        tabSucursales.setLayout(new java.awt.BorderLayout());
        tabHolder.addTab("SUCURSALES", tabSucursales);

        tabVentas.setLayout(new java.awt.BorderLayout());
        tabHolder.addTab("VENTAS", tabVentas);

        tabEmpleados.setLayout(new java.awt.BorderLayout());
        tabHolder.addTab("EMPLEADOS", tabEmpleados);

        tabProductos.setLayout(new java.awt.BorderLayout());
        tabHolder.addTab("PRODUCTOS", tabProductos);

        tabClientes.setLayout(new java.awt.BorderLayout());
        tabHolder.addTab("CLIENTES", tabClientes);

        tabReportes.setLayout(new java.awt.BorderLayout());
        tabHolder.addTab("REPORTES", tabReportes);

        jPanel2.add(tabHolder, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Actualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ps.update();
        pe.update();
        pp.update();
        pc.update();
        pv.update();
        pr.update();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel tabClientes;
    private javax.swing.JPanel tabEmpleados;
    private javax.swing.JTabbedPane tabHolder;
    private javax.swing.JPanel tabProductos;
    private javax.swing.JPanel tabReportes;
    private javax.swing.JPanel tabSucursales;
    private javax.swing.JPanel tabVentas;
    // End of variables declaration//GEN-END:variables
}
