/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Front;

import DAO.InventarioDAO;
import DAO.ProductoDAO;
import DataClasses.Empleado;
import DataClasses.Inventario;
import java.text.ParseException;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OrdSon
 */
public class PanelBodega extends javax.swing.JPanel {
    
    Empleado empleado;
    String nombre;
    
    ProductoDAO productoDAO = new ProductoDAO();
    InventarioDAO inventarioDAO = new InventarioDAO();

    /**
     * Creates new form PanelInventario
     */
    public PanelBodega() {
        initComponents();
        this.setVisible(true);
        fillTables();

    }
    
    public PanelBodega(Empleado empleado){
        this.empleado = empleado;
        initComponents();
        this.setVisible(true);
        LinkedList<Inventario> slot = inventarioDAO.select(new Inventario(0, "", "", empleado.sucursal(), "", 0));
        if(!slot.isEmpty()){
            this.nombre = slot.getFirst().nombreSucursal();
            this.tituloLbl.setText(nombre);
        }
        fillTables();
    }

    private void fillTables() {
        productosTabla.setModel(productoDAO.getTableModel(productoDAO.selectAll()));
        inventarioTabla.setModel(inventarioDAO.getTableModel(inventarioDAO.selectAll(empleado.sucursal())));
        updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        idTxt = new javax.swing.JTextField();
        marcaTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cantidadSpinner = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productosTabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inventarioTabla = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        idTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("ID PRODUCTO"));

        marcaTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("MARCA"));

        nombreTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE PRODUCTO"));

        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cantidadSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantidadSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));
        cantidadSpinner.setFocusable(false);

        jButton2.setText("Retirar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(cantidadSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel8.setLayout(new java.awt.BorderLayout());

        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("txt");
        jPanel8.add(tituloLbl, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        productosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productosTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosTablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productosTabla);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tabPanel.addTab("PRODUCTOS", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        inventarioTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        inventarioTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventarioTablaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(inventarioTabla);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabPanel.addTab("INVENTARIO", jPanel3);

        jPanel1.add(tabPanel, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void productosTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosTablaMouseClicked
        getProductRowData();
    }//GEN-LAST:event_productosTablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        insertar(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void insertar(boolean negativo) {
        if (idTxt.getText().isBlank() && nombreTxt.getText().isBlank() && marcaTxt.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Alguno de los campos debe contener información \nPuede seleccionar un producto haciendo click sobre el");
            return;
        }
        if (idTxt.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Necesita seleccionar un producto\nPuede seleccionar un producto haciendo click sobre el");
            return;
        }
        inventarioDAO.insert(recopilarObjeto(negativo));
    }
    private void inventarioTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioTablaMouseClicked
        getInventoryRowData();
        fillTables();
    }//GEN-LAST:event_inventarioTablaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insertar(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    private Inventario recopilarObjeto(boolean negativo) {
        try {
            int id = Integer.parseInt(idTxt.getText());
            String nombre = nombreTxt.getText();
            String marca = marcaTxt.getText();
            cantidadSpinner.commitEdit();
            int cant = (Integer) cantidadSpinner.getValue();
            if (negativo) {
                cant = (cant * -1);
            }
            return new Inventario(id, nombre, marca, empleado.sucursal(),nombre , cant);
        } catch (NumberFormatException | ParseException e) {
            return null;
        }
    }

    private void getProductRowData() {
        DefaultTableModel model = (DefaultTableModel) productosTabla.getModel();
        int selectedRowIndex = productosTabla.getSelectedRow();
        idTxt.setText(model.getValueAt(selectedRowIndex, 0).toString());
        marcaTxt.setText(model.getValueAt(selectedRowIndex, 1).toString());
        nombreTxt.setText(model.getValueAt(selectedRowIndex, 3).toString());

    }

    private void getInventoryRowData() {
        DefaultTableModel model = (DefaultTableModel) inventarioTabla.getModel();
        int selectedRowIndex = inventarioTabla.getSelectedRow();
        idTxt.setText(model.getValueAt(selectedRowIndex, 0).toString());
        marcaTxt.setText(model.getValueAt(selectedRowIndex, 2).toString());
        nombreTxt.setText(model.getValueAt(selectedRowIndex, 1).toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JTextField idTxt;
    private javax.swing.JTable inventarioTabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTable productosTabla;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
